sudo: required

language: java
env: DOCKER_USERNAME=scp1920

services:
  - docker

before_install:
  - bash docker_login.sh $DOCKER_USERNAME $DOCKER_PASSWORD

install:
  - docker pull $DOCKER_USERNAME/dronizone:order
  - docker pull $DOCKER_USERNAME/dronizone:warehouse
  - docker pull $DOCKER_USERNAME/dronizone:notification

before_script:
  - mvn clean package -DskipTests
  - docker run -d -p 9002:9002 -t $DOCKER_USERNAME/dronizone:warehouse
  - docker run -d -p 9001:9001 -t $DOCKER_USERNAME/dronizone:order

script:
  - cd dronizone-order
  - mvn test
  - cd ../dronizone-notification
  - docker-compose up --build -d
  - mvn test
  - cd ../dronizone-fleet
  - mvn test

notifications:
  email:
    recipients:
      - valentin.ah-kane@etu.univ-cotedazur.fr
      - filipe.costa-de-sousa@etu.univ-cotedazur.fr
      - romain.garnier@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr

