sudo: required

language: java

services:
  - docker

install:
  - mvn clean install -DskipTests

before_script:
  - docker-compose up --build -d

script:
  - cd dronizone-notification
  - mvn test

notifications:
  email:
    recipients:
      - valentin.ah-kane@etu.univ-cotedazur.fr
      - filipe.costa-de-sousa@etu.univ-cotedazur.fr
      - romain.garnier@etu.univ-cotedazur.fr
      - cyril.marilier@etu.univ-cotedazur.fr

